### PR TITLE
Fix people can open car crashing windows. Fix commented by https://gi…

### PR DESCRIPTION
**Pull request by behindlife**
…thub.com/TKLeuPT #2

People can open car and up inside the car when push F 2 or more times. This fix clean this option people can't enter or crash windows. 

Thanks TKLeuPT

### CODE REVIEW

**Comment by chasen-bettinger** [comment]
What is the status of this?

**Comment by behindlife** [comment]
> What is the status of this?

Its for make sure cars no open and no pull windows, the character do animation to open all time but can't open the car and no crash the window. This fix is thanks by TKLeuPT.

**Comment by chasen-bettinger** [comment]
Yeah I know what this does, why is it just lingering?

**Comment by behindlife** [comment]
> Yeah I know what this does, why is it just lingering?

The reason is simple if u no have a mod to thief car's this fix is pretty for RP servers, all time people make first connect in u server and search a car to steal it without roleplay. U have others scripts to put in the server to make a thiefcar esx_thiefcar and others in fivem forum, this is the reason to lock good the cars to new users enter in rp server can't steal cars without roleplaying. ( No more reason for this. ) u ensure the cars can't open by any if lock. Unique owner can unlock and enter. Its a nice for RP servers without whitelist. I think.

**Comment by BackrndSource** [comment]
thanks dude! I just came to update the script but I see that you already did it. Works perfect for RP

**Comment by behindlife** [comment]
> thanks dude! I just came to update the script but I see that you already did it. Works perfect for RP

Np Thanks u by translate all scripts to spanish, im from Barcelona and im very happinest i see people sending translate in scripts from esx :D

**Pull request closed without merging**
